pila/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls'))
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("<int:todo_id>/update", views.update, name="update"),
    path("<int:todo_id>/delete", views.delete, name="delete"),
]

todo/models.py
from django.db import models

# Create your models here.

class Todo (models.Model):
    name = models.CharField(max_length=255)
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def is_done(self):
        return self.done

pila/views.py
from django.http import HttpResponse
import datetime

def current_datetime(request):
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return HttpResponse(html)

todo/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse

# Create your views here.
from .models import Todo

def index (request):
    todos = Todo.objects.order_by('-id') 
    return render(request, 'index.html', {'todos': todos, 'length': len(todos)})

def add (request):

    name = request.POST.get('todo-add')
    if (name == ''):
        return HttpResponseRedirect(reverse('todo:index'))

    todo = Todo(name=name)
    todo.save()
    return HttpResponseRedirect(reverse('todo:index'))

def update (request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    
    if (todo.done):
        todo.done = False
    else:
        todo.done = True
    
    todo.save()
    return HttpResponseRedirect(reverse('todo:index'))

def delete (request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.delete()
    return HttpResponseRedirect(reverse('todo:index'))


todo/templates/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />

		{% load static %}

		<link rel="stylesheet" href="{% static 'style.css' %}" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
			crossorigin="anonymous"
		/>

		<title>Todo App</title>
	</head>
	<body>
		<div class="banner bg-info bg-gradient">
			<h1 class="title">Todo application</h1>

			<form action="{% url 'todo:add' %}" class="todo-field" method="post">
				{% csrf_token %}
				<fieldset>
					<label for="todo-add" class="form-label">Add a todo</label>
					<input
						type="text"
						class="form-control"
						id="todo-add"
						name="todo-add"
						value=""
						placeholder="Add todo"
					/>
				</fieldset>
			</form>
		</div>

		<div class="container">
			<h1 class="my-3 mx-2">Todo List</h1>

			{% if length == 0 %}
			<div class="card">
				<div class="card-body">There is no todo in the list, add one</div>
			</div>
			{% endif %}

			<ul class="list-group">
				{% for todo in todos %}
				<li class="list-group-item" aria-current="true">
					<div class="todo-item">
						<form
							class="todo-check"
							action="{% url 'todo:update' todo.id %}"
							method="post"
							id="form-todo-{{ todo.id }}"
						>
							<span>{{ forloop.counter }}</span>
							<input type="checkbox" data-todo_id="{{ todo.id }}" name="todo-{{
							todo.id }}" id="todo-{{ todo.id }}" {% if todo.done == True %}
							checked {% endif %} />

							<span class="todo-name">{{ todo }}</span>

							{% csrf_token %}
						</form>

						<div class="todo-delete">
							<form action="{% url 'todo:delete' todo.id %}" method="post">
								{% csrf_token %}
								<button type="submit" class="btn btn-secondary">
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="16"
										height="16"
										fill="currentColor"
										class="bi bi-trash"
										viewBox="0 0 16 16"
									>
										<path
											d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"
										/>
										<path
											d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"
										/>
									</svg>
									Delete
								</button>
							</form>
						</div>
					</div>
				</li>
				{% endfor %}
			</ul>
		</div>

		<script>
			document.querySelectorAll("input[data-todo_id]").forEach((element) => {
				element.addEventListener("click", function (event) {
					const id = element.dataset["todo_id"];

					const form = document.getElementById("form-todo-" + id);

					form.submit();
				});
			});
		</script>

		<!-- Option 2: Separate Popper and Bootstrap JS -->
		<!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
	</body>
</html>